@startuml
title WOF Portal - Client interaction overview

skinparam sequenceArrowThickness 2
skinparam sequenceGroupBorderThickness 1
skinparam noteBorderColor #888888
skinparam noteBackgroundColor #FFFFEE

actor "Scheduling Client" as Client
control "Auth Endpoint" as Auth
control "WOF Portal API" as Portal

note over Client,Portal
  basePath = {{baseUrl}}/{{tenant}}/{{apiVersion}}/R4/fhir
end note

== System token ==

Client -> Auth : POST {{basePath}}/auth/system-token
note over Client,Auth
  Header: X-ApiKey {{apiKey}}
end note
Auth --> Client : access_token

== HealthcareService ==

Client -> Portal : GET {{basePath}}/HealthcareService
Client -> Portal : GET {{basePath}}/HealthcareService/{{healthcareServiceId}}
Client -> Portal : GET {{basePath}}/HealthcareService/{{healthcareServiceId}}/$get-offers-context\n?includeActivityDefinitionPortal={{includeAD}}\n&includePractitionerRolePortal={{includePR}}

== Root operation ==

Client -> Portal : GET {{basePath}}/$get-offers-context\n?includeActivityDefinitionPortal={{includeAD}}\n&includeHealthcareServicePortal={{includeHS}}\n&includePractitionerRolePortal={{includePR}}

== ActivityDefinition ==

Client -> Portal : GET {{basePath}}/ActivityDefinition
Client -> Portal : GET {{basePath}}/ActivityDefinition/{{activityDefinitionId}}
Client -> Portal : GET {{basePath}}/ActivityDefinition/{{activityDefinitionId}}/$get-offers-context\n?includeActivityDefinitionPortal={{includeAD}}\n&includeHealthcareServicePortal={{includeHS}}\n&includePractitionerRolePortal={{includePR}}
Client -> Portal : GET {{basePath}}/ActivityDefinition/{{activityDefinitionId}}/$get-offers-context

== PractitionerRole ==

Client -> Portal : GET {{basePath}}/PractitionerRole
Client -> Portal : GET {{basePath}}/PractitionerRole/{{practitionerRoleId}}
Client -> Portal : GET {{basePath}}/PractitionerRole/{{practitionerRoleId}}/$get-offers-context\n?includeActivityDefinitionPortal={{includeAD}}\n&includeHealthcareServicePortal={{includeHS}}\n&includePractitionerRolePortal={{includePR}}

== Catalog resources ==

Client -> Portal : GET {{basePath}}/Location
Client -> Portal : GET {{basePath}}/Organization

== IHE Scheduling find ==

Client -> Portal : GET {{basePath}}/Appointment/$find\n?start={{find_start}}&end={{find_end}}\n&visit-type={{visitTypeSystem}}|{{visitTypeCode}}\n&healthcareService=HealthcareService/{{healthcareServiceId}}\n&practitionerRole=PractitionerRole/{{practitionerRoleId}}

@enduml